fix(dcmjs): #231 Fix the normalize Alphabetic twice
dcmjs-org/dcmjs pull request #237
Opened 2022-01-28 13:43 UTC by wayfarer3130

Fixed issue 231 where normalizing twice fails, and prevents side affects for modifying the array of length one, but doesn't fix any of the issues modifying longer non-sequence arrays, nor modifications to the properties of the child objects.

2022-01-28 16:43 UTC, pieper requested changes
Can you add some more description in your commit message?  Why did the previous code lead to the issue, what changes did you make and why did they fix the problem?  It will help to have more context if this or a related issue comes up again.

2022-01-28 16:43 UTC, pieper commented on test/test_data.js
> +        const natural0b = DicomMetaDictionary.naturalizeDataset(datasets[0]);
Can you also test if they are the same?

2022-02-24 02:43 UTC, wayfarer3130 commented on test/test_data.js
> +        const natural0b = DicomMetaDictionary.naturalizeDataset(datasets[0]);
Yes, done.

2022-02-24 02:44 UTC, wayfarer3130 commented
> Can you add some more description in your commit message? Why did the previous code lead to the issue, what changes did you make and why did they fix the problem? It will help to have more context if this or a related issue comes up again.

Redid the commit message when I added the other fix and updated to master.

2022-02-24 15:51 UTC, pieper approved these changes
Thanks for the updates 👍

2022-02-24 15:52 UTC, merged